"use strict";

require('./inheritance-clientserver.js')

var UnstudiedWord = require('./UnstudiedWord')
var Word = require('./Word')
var typecheck = require('./typecheck')

/**
 * An inflection of a word generated by Inflection. The facts assumed to be required to know it are a grammar rule
 * defining how to inflect the form (e.g. by adding an ending) and the base form; the word itself is not a fact.
 */
var Inflection = UnstudiedWord.extend({
    /**
     * @param infinitive Word representing the base form.
     */
    init: function(jp, infinitive) {
        typecheck(arguments, 'string', Word)

        this.jp = jp
        this.infinitive = infinitive
        this.en = {}
    },

    /**
     * The knowledge required for an inflection is the base form of the word as well as any gramar rules used to
     * derive it.
     */
    visitFacts: function(visitor) {
        visitor(this.infinitive)

        this.visitRequired(visitor)
    }
})

module.exports = Inflection