// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/883f016ef7dd32f43f4d36444ccb10d94910e718/html-entities/html-entities.d.ts
declare module "html-entities" {
    abstract class Entities {
        encode(toEncode: string): string;
        encodeNonUTF(toEncode: string): string;
        encodeNonASCII(toEncode: string): string;
        decode(toDecode: string): string;
    }
    class XmlEntities extends Entities {}
    class Html4Entities extends Entities {}
    class Html5Entities extends Entities {}
    class AllHtmlEntities extends Entities {}
}